export const elements = {
  app: document.querySelector("#app"),
  container: document.querySelector(".container"),
  searchForm: document.querySelector("#search-form"),
  weather: document.querySelector("#weather"),
  location: document.querySelector(".city"),
  pin: document.querySelector(".fa-location-pin"),
  search: document.querySelector(".search"),
  error: document.querySelector(".error"),
  icon: document.querySelector(".icon"),
  degrees: document.querySelector(".degrees"),
  description: document.querySelector(".weather-description"),
  feelsLike: document.querySelector(".feels-like"),
  humidity: document.querySelector(".humidity"),
  sunrise: document.querySelector(".sunrise"),
  sunset: document.querySelector(".sunset"),
  windDirection: document.querySelector(".wind-direction"),
  windSpeed: document.querySelector(".wind-speed"),
  gifBG: document.querySelector(".background-gif"),
};
